### ISSUE TITLE
CI / CD Pipeline

### ISSUE THREAD

**Issue by rasaford** [naklar-io/naklar.io#10]
How about we run a CI / CD server, executing tests on both front- / backend apis and automatically deploying a version of the site (i.e. on a deploy branch)?

**Discussion wanted ;)**

**Comment by nylser** [comment]
Seems good! I don't know how easy it will be for django as we might have to make migrations (maybe add new default values). Maybe a script that always pulls the newest version, executes migrations and starts the server. might be susceptible to breaking though

**Comment by nylser** [comment]
This is now done (exluding production). Every new change to the master branch is automatically deployed to dev.naklar.io and dev.api.naklar.io respectively.
