### ISSUE TITLE
SEO

### ISSUE THREAD

**Issue by rasaford** [naklar-io/naklar.io#54]
Improve the search ranking for the page. Usefull ressources:

- [Medium Guide](https://medium.com/slalom-build/bringing-seo-to-angular-applications-9de14995dc67)
- [Internal SEO Linking](https://yoast.com/internal-linking-for-seo-why-and-how/), [Also on MDN](https://moz.com/learn/seo/internal-link)
- [Google Mobile Friendly Tester](https://search.google.com/test/mobile-friendly)

Will definitely be improved by #53

**Comment by nylser** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [SEO Texte](https://trello.com/c/5qkCQzIl/4-seo-texte)
